name: bruin-pipeline
schedule: "0 6 * * 1"
start_date: "2025-06-01"

default_connections:
  bigquery: gcp

python:
  executable: .venv/bin/python

variables:
  gcs_bucket_name:
    type: string
    default: "project-d79af39f-8a71-4f5d-812-maddison-project"
  gcp_project_id:
    type: string
    default: "project-d79af39f-8a71-4f5d-812"